import { TaskTreeDB } from './task-tree-db';
import { ProcessLogDB } from './process-log-db';
import { AgentMessageDB } from './agent-message-db';
import type { TaskTreeRow, AgentProcessLogRow, AgentMessageRow } from '@/db/types';
import type { ModuleContract } from './types';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RecoveryContext {
  /** The task node being recovered. */
  task: TaskTreeRow;
  /** The last process log entry, or null if none exist. */
  lastLog: AgentProcessLogRow | null;
  /** File paths already generated by this task (from output_files_json). */
  generatedFiles: string[];
  /** Parsed contract JSON, or null. */
  contract: ModuleContract | null;
  /** Unresolved inter-agent messages for this task. */
  unresolvedMessages: AgentMessageRow[];
}

// ---------------------------------------------------------------------------
// RecoveryService
// ---------------------------------------------------------------------------

export class RecoveryService {
  private taskDB = new TaskTreeDB();
  private logDB = new ProcessLogDB();
  private msgDB = new AgentMessageDB();

  /**
   * Get all unfinished tasks for a project, ordered by depth ascending
   * (shallow first so architect-level tasks recover before developer tasks).
   */
  async getUnfinishedTasks(projectName: string): Promise<TaskTreeRow[]> {
    return this.taskDB.getUnfinished(projectName);
  }

  /**
   * Build a recovery context for a specific task node.
   * Returns the last log entry, list of already-generated files,
   * parsed contract JSON, and any unresolved inter-agent messages.
   */
  async buildRecoveryContext(taskId: string): Promise<RecoveryContext> {
    const task = await this.taskDB.getById(taskId);
    if (!task) {
      throw new Error(`Task not found: ${taskId}`);
    }

    const lastLog = await this.logDB.getLastStep(taskId);

    const generatedFiles: string[] = task.output_files_json
      ? (JSON.parse(task.output_files_json) as string[])
      : [];

    let contract: ModuleContract | null = null;
    if (task.contract_json) {
      try {
        contract = JSON.parse(task.contract_json) as ModuleContract;
      } catch {
        // contract_json may hold a non-ModuleContract JSON (e.g. a
        // requirement blob for the root task); that is fine.
      }
    }

    const unresolvedMessages = await this.msgDB.getUnresolved(taskId);

    return { task, lastLog, generatedFiles, contract, unresolvedMessages };
  }

  /**
   * Alias for buildRecoveryContext.  Loads existing files, last state,
   * contract, and unresolved messages so the agent can continue.
   */
  async resumeTask(taskId: string): Promise<RecoveryContext> {
    return this.buildRecoveryContext(taskId);
  }
}
